<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MiniCPQ.Domain\MiniCPQ.Domain.csproj" />
    <ProjectReference Include="..\MiniCPQ.Application\MiniCPQ.Application.csproj" />
    <ProjectReference Include="..\MiniCPQ.Infrastructure\MiniCPQ.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
